[package]
name = "flux-notify"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
members = ["lib/api"]
resolver = "2"

[dependencies]
flux-notify-api = { path = "lib/api" }

anyhow = "1.0.93"
thiserror = "2.0.3"
config = "0.14.1"

axum = "0.7.9"

tokio = { version = "1.41.1", features = ["full"] }

tonic = "0.12.3"
tonic-health = "0.12.3"
tonic-reflection = "0.12.3"

serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
